terracotta-education/terracotta

src/main/java/edu/iu/terracotta/model/app/Experiment.java
src/main/java/edu/iu/terracotta/model/app/dto/ConditionDto.java
src/main/java/edu/iu/terracotta/model/app/dto/ParticipantDto.java

Removed a few unneeded comments/TODO's

Changed boolean to Boolean to handle NullPointerExceptions.

---

src/main/java/edu/iu/terracotta/controller/app/AssignmentController.java
src/main/java/edu/iu/terracotta/controller/app/ConditionController.java
src/main/java/edu/iu/terracotta/controller/app/ExposureController.java
src/main/java/edu/iu/terracotta/controller/app/ParticipantController.java
src/main/java/edu/iu/terracotta/controller/app/RestResponseEntityExceptionHandler.java
src/main/java/edu/iu/terracotta/exceptions/AssignmentNotMatchingException.java
src/main/java/edu/iu/terracotta/model/app/Assignment.java
src/main/java/edu/iu/terracotta/model/app/dto/AssignmentDto.java
src/main/java/edu/iu/terracotta/repository/AllRepositories.java
src/main/java/edu/iu/terracotta/repository/AssignmentRepository.java
src/main/java/edu/iu/terracotta/service/app/APIJWTService.java
src/main/java/edu/iu/terracotta/service/app/AssignmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/APIJWTServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/utils/TextConstants.java
src/main/resources/db/changelog/2021/05/24-01-changelog.xml
src/main/resources/db/changelog/2021/05/25-01-changelog.xml
src/main/resources/db/changelog/2021/05/26-01-changelog.xml
src/main/resources/db/changelog/changelog-master.xml

Fixed bug with exceptions.
Fixed ucBuilder path 'experiments' from 'experiment'

Added base Assignment design and functionality.

---

src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/RestResponseEntityExceptionHandler.java
src/main/java/edu/iu/terracotta/model/app/Answer.java
src/main/java/edu/iu/terracotta/model/app/Question.java
src/main/java/edu/iu/terracotta/model/app/dto/AnswerDto.java
src/main/java/edu/iu/terracotta/model/app/dto/QuestionDto.java
src/main/java/edu/iu/terracotta/service/app/AnswerService.java
src/main/java/edu/iu/terracotta/service/app/QuestionService.java
src/main/java/edu/iu/terracotta/service/app/impl/AnswerServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java
src/main/resources/db/changelog/2021/05/01-01-changelog.xml
src/main/resources/db/changelog/changelog-master.xml

(Ability to PUT lists of questions or answers)

Added order to Questions and Answers.

---

src/main/java/edu/iu/terracotta/controller/app/ParticipantController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionController.java

Bug in import

---

src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/OutcomeController.java
src/main/java/edu/iu/terracotta/controller/app/OutcomeScoreController.java
src/main/java/edu/iu/terracotta/controller/app/ParticipantController.java
src/main/java/edu/iu/terracotta/controller/app/RestResponseEntityExceptionHandler.java
src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/exceptions/OutcomeNotMatchingException.java
src/main/java/edu/iu/terracotta/exceptions/OutcomeScoreNotMatchingException.java
src/main/java/edu/iu/terracotta/model/app/Exposure.java
src/main/java/edu/iu/terracotta/model/app/Outcome.java
src/main/java/edu/iu/terracotta/model/app/OutcomeScore.java
src/main/java/edu/iu/terracotta/model/app/dto/OutcomeDto.java
src/main/java/edu/iu/terracotta/model/app/dto/OutcomeScoreDto.java
src/main/java/edu/iu/terracotta/model/app/enumerator/LmsType.java
src/main/java/edu/iu/terracotta/repository/AllRepositories.java
src/main/java/edu/iu/terracotta/repository/OutcomeRepository.java
src/main/java/edu/iu/terracotta/repository/OutcomeScoreRepository.java
src/main/java/edu/iu/terracotta/repository/ParticipantRepository.java
src/main/java/edu/iu/terracotta/service/app/APIJWTService.java
src/main/java/edu/iu/terracotta/service/app/OutcomeScoreService.java
src/main/java/edu/iu/terracotta/service/app/OutcomeService.java
src/main/java/edu/iu/terracotta/service/app/ParticipantService.java
src/main/java/edu/iu/terracotta/service/app/impl/APIJWTServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/OutcomeScoreServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/OutcomeServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/ParticipantServiceImpl.java
src/main/java/edu/iu/terracotta/utils/TextConstants.java
src/main/resources/db/changelog/2021/05/10-02-changelog.xml
src/main/resources/db/changelog/changelog-master.xml

Participants are no longer deleted, attribute 'dropped' is marked as true.

Added Outcomes and Outcome Scores.

---

src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionCommentController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionController.java
src/main/java/edu/iu/terracotta/controller/app/SubmissionCommentController.java
src/main/java/edu/iu/terracotta/controller/app/SubmissionController.java
src/main/java/edu/iu/terracotta/repository/QuestionSubmissionRepository.java
src/main/java/edu/iu/terracotta/repository/SubmissionCommentRepository.java
src/main/java/edu/iu/terracotta/repository/SubmissionRepository.java
src/main/java/edu/iu/terracotta/service/app/QuestionSubmissionService.java
src/main/java/edu/iu/terracotta/service/app/SubmissionCommentService.java
src/main/java/edu/iu/terracotta/service/app/SubmissionService.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionSubmissionServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/SubmissionCommentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/SubmissionServiceImpl.java

Students are only able to access their own submissions and anything that goes through the path of submissions (submission comments, question submissions, question submission comments). Only the creator of a comment is allowed to edit the comment.

Security Update

---

src/main/java/edu/iu/terracotta/controller/app/FileController.java
src/main/java/edu/iu/terracotta/model/app/FileInfo.java
src/main/java/edu/iu/terracotta/repository/AllRepositories.java
src/main/java/edu/iu/terracotta/repository/FileInfoRepository.java
src/main/java/edu/iu/terracotta/service/app/FileStorageService.java
src/main/java/edu/iu/terracotta/service/app/impl/FileStorageServiceImpl.java
src/main/resources/db/changelog/2021/05/15-01-changelog.xml
src/main/resources/db/changelog/changelog-master.xml

file uploads now have their path stored in a table in the DB and are accessed through a UUID.

Change to file uploading.

---

src/main/java/edu/iu/terracotta/controller/app/ExperimentController.java
src/main/java/edu/iu/terracotta/controller/app/FileController.java
src/main/java/edu/iu/terracotta/repository/ExperimentRepository.java
src/main/java/edu/iu/terracotta/service/app/ExperimentService.java
src/main/java/edu/iu/terracotta/service/app/impl/ExperimentServiceImpl.java

Consent Assignment default title changed.

Cannot create experiments with duplicate titles

---

src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/AssignmentController.java
src/main/java/edu/iu/terracotta/controller/app/ConditionController.java
src/main/java/edu/iu/terracotta/controller/app/ExperimentController.java
src/main/java/edu/iu/terracotta/controller/app/ExposureController.java
src/main/java/edu/iu/terracotta/controller/app/GroupController.java
src/main/java/edu/iu/terracotta/controller/app/OutcomeController.java
src/main/java/edu/iu/terracotta/repository/ConditionRepository.java
src/main/java/edu/iu/terracotta/repository/ExperimentRepository.java
src/main/java/edu/iu/terracotta/service/app/ConditionService.java
src/main/java/edu/iu/terracotta/service/app/impl/ConditionServiceImpl.java

All titles/names have a character limit check.
Experiment and Condition titles must be populated in the PUT.
A default condition cannot be deleted.

Bug fixes.

---

src/main/java/edu/iu/terracotta/controller/app/AnswerController.java
src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/AssignmentController.java
src/main/java/edu/iu/terracotta/controller/app/ConditionController.java
src/main/java/edu/iu/terracotta/controller/app/ExposureController.java
src/main/java/edu/iu/terracotta/controller/app/GroupController.java
src/main/java/edu/iu/terracotta/controller/app/OutcomeController.java
src/main/java/edu/iu/terracotta/controller/app/OutcomeScoreController.java
src/main/java/edu/iu/terracotta/controller/app/ParticipantController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionCommentController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionController.java
src/main/java/edu/iu/terracotta/controller/app/SubmissionCommentController.java
src/main/java/edu/iu/terracotta/controller/app/SubmissionController.java
src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/service/app/AnswerService.java
src/main/java/edu/iu/terracotta/service/app/impl/AnswerServiceImpl.java

Students are unable to view whether an answer is correct or not.

Security update.

---

src/main/java/edu/iu/terracotta/controller/app/FileController.java
src/main/java/edu/iu/terracotta/service/app/AssignmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/OutcomeServiceImpl.java
src/main/java/edu/iu/terracotta/service/canvas/CanvasAPIClient.java
src/main/java/edu/iu/terracotta/service/canvas/impl/CanvasAPIClientImpl.java

First part of rebuild assignments deleted.

Repair Canvas API calls.

---

pom.xml
src/main/java/edu/iu/terracotta/config/WebSecurityConfig.java
src/main/java/edu/iu/terracotta/controller/app/FileDownloadController.java
src/main/java/edu/iu/terracotta/model/app/dto/FileInfoDto.java
src/main/java/edu/iu/terracotta/service/app/APIJWTService.java
src/main/java/edu/iu/terracotta/service/app/FileStorageService.java
src/main/java/edu/iu/terracotta/service/app/impl/APIJWTServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AnswerServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/ExperimentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/FileStorageServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java

This will parse the HTML and replace any file reference with one with a temporal token to download it.

Generate file URL with temporal token to download it.

---

src/main/java/edu/iu/terracotta/service/app/impl/ConditionServiceImpl.java

Provided a more detailed error message explaining the possible issue

TCOTA-232 (temporary fix): duplicate condition name bug.

---

src/main/java/edu/iu/terracotta/service/app/impl/ExportServiceImpl.java
src/main/java/edu/iu/terracotta/service/caliper/impl/CaliperServiceImpl.java

- TCOTA-370 Scrub non-consenting participants from events export
- TCOTA-371 Remove personal identifiers from events data

TCOTA-370 TCOTA-371 Filtering exported events

---

src/main/javascript/src/router/index.js
src/main/javascript/src/services/submission.service.js
src/main/javascript/src/views/grading/AssignmentScores.vue
src/main/javascript/src/views/grading/StudentSubmissionGrading.vue

Adds submission_id to the StudentSubmissionGrading route to
distinguish multiple submissions for a participant

TCOTA-362 Fix display of multiple submissions

---

src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/service/app/AssessmentService.java
src/main/java/edu/iu/terracotta/service/app/QuestionService.java
src/main/java/edu/iu/terracotta/service/app/TreatmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/QuestionServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImplTest.java

Implementing the feature for duplicating a treatment. This also duplicates the assessment and questions (no submissions are duplicated).
This is BACKEND only.

TCOTA-514 TCOTA-520 implement duplicate treatment feature (backend)

---

src/main/java/edu/iu/terracotta/controller/app/AssignmentController.java
src/main/java/edu/iu/terracotta/service/app/AssignmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImplTest.java

Implementing the feature for duplicating an assignment.
This is BACKEND only.

TCOTA-515 TCOTA-524 implement duplicate assignment feature (backend)

---

src/main/javascript/src/views/ExperimentSummary.vue
src/main/javascript/src/views/ExperimentSummaryStatus.vue

This feature moves the Design, Participants, and Assignments content sections to their own respective tabs.

TCOTA-511 TCOTA-512 Moved accordion content to tab navigation

---

src/main/java/edu/iu/terracotta/controller/app/RestResponseEntityExceptionHandler.java
src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/exceptions/AssignmentLockedException.java
src/main/java/edu/iu/terracotta/service/app/APIJWTService.java
src/main/java/edu/iu/terracotta/service/app/impl/APIJWTServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java

Implemented a new assignment locked security check. It checks to see if the assignment has been started, if so, throws an exception.

TCOTA-517 TCOTA-535 implement assignment locked security check

---

src/main/java/edu/iu/terracotta/controller/app/AssignmentController.java
src/main/java/edu/iu/terracotta/model/app/Assignment.java
src/main/java/edu/iu/terracotta/repository/AssignmentRepository.java
src/main/java/edu/iu/terracotta/service/app/AssignmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/ExportServiceImpl.java
src/main/resources/db/changelog/2022.09/08-01-changelog.xml
src/main/resources/db/changelog/changelog-master.xml
src/test/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImplTest.java

Implementing the feature for deleting an assignment.
This is BACKEND only.

TCOTA-516 TCOTA-525 implementing delete assignment link (backend)

---

src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionController.java
src/main/java/edu/iu/terracotta/controller/app/RestResponseEntityExceptionHandler.java
src/main/java/edu/iu/terracotta/controller/app/StepsController.java
src/main/java/edu/iu/terracotta/exceptions/AssignmentAttemptException.java
src/main/java/edu/iu/terracotta/model/app/Assessment.java
src/main/java/edu/iu/terracotta/service/app/AssignmentService.java
src/main/java/edu/iu/terracotta/service/app/QuestionSubmissionService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionSubmissionServiceImpl.java
src/main/java/edu/iu/terracotta/utils/TextConstants.java
src/test/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImplTest.java

Added the features to retry an assignment. We now check for number of submissions already attempted and the wait time between submissions. Refactored a bit of the code for readability and added missing unit tests.

TCOTA-494 TCOTA-527 implement feature for assignment retry (backend)

---

src/main/java/edu/iu/terracotta/model/app/Assignment.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java

Removed the setSoftDeleted field on the fromDTO(), as the UI should not set this field anyway... and changed to Boolean on the Assignment.softDeleted filed as a precaution.

TCOTA-493 TCOTA-544 fix NPE

---

src/main/java/edu/iu/terracotta/repository/AssignmentRepository.java

Removed the hardcoded SQL, as it doesn't handle foreign keys... let JPA do the work :)

TCOTA-493 TCOTA-545 fix deleteByAssignmentId() error

---

src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/exceptions/IdMismatchException.java
src/main/java/edu/iu/terracotta/service/app/TreatmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImpl.java
src/main/java/edu/iu/terracotta/utils/TextConstants.java
src/test/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImplTest.java

Added the service layer behind the PUT treatment endpoint to enable that service for the UI. Added new unit tests as well.

TCOTA-514 TCOTA-547 enable PUT endpoint for treatments

---

src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/AnswerServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/ExportServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/GroupServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/ParticipantServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/QuestionServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/QuestionSubmissionServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/SubmissionServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImplTest.java

Last PR was merged before I could fix the test errors from merge conflicts :)

TCOTA-493 TCOTA-553 fixing tests from merge conflict fixes

---

src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/service/app/AssessmentService.java
src/main/java/edu/iu/terracotta/service/app/TreatmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImplTest.java

Fix the PUT treatments endpoint to handle assessment question adds/updates/deletes.
Added unit tests.

TCOTA-514 TCOTA-547 fix PUT endpoint for treatments

---

src/main/java/edu/iu/terracotta/controller/app/AnswerController.java
src/main/java/edu/iu/terracotta/service/app/AnswerService.java
src/main/java/edu/iu/terracotta/service/app/impl/AnswerServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/ExportServiceImplTest.java

- Updated PUT answer controllers, return updated Answer DTOs
- Updated the GET questions service to honor the boolean to include correct answers
- Fixed broken unit tests

TCOTA-565 fix MC answers read/write issues

---

src/main/java/edu/iu/terracotta/model/app/Question.java
src/main/java/edu/iu/terracotta/repository/AnswerMcRepository.java
src/main/java/edu/iu/terracotta/repository/AssignmentRepository.java
src/main/java/edu/iu/terracotta/repository/QuestionRepository.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/resources/db/changelog/2022.10/06-01-changelog.xml
src/main/resources/db/changelog/changelog-master.xml
src/test/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImplTest.java

- added the treatment copy functionality
- fixed JPA database cascading issue for MC question join table

TCOTA-554 TCOTA-556 fixing assignment move issues

---

src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/AssignmentController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionController.java
src/main/java/edu/iu/terracotta/controller/app/TreatmentController.java
src/main/java/edu/iu/terracotta/service/app/AssessmentService.java
src/main/java/edu/iu/terracotta/service/app/AssignmentService.java
src/main/java/edu/iu/terracotta/service/app/QuestionService.java
src/main/java/edu/iu/terracotta/service/app/TreatmentService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/ParticipantServiceImplTest.java
src/test/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImplTest.java

Fixed copying of MC options and settings.

TCOTA-493 TCOTA-514 fixing copy treatment issues

---

src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/QuestionServiceImplTest.java

TCOTA-514 fix NPE on questionDto.getAnswers() in POST

---

src/main/java/edu/iu/terracotta/model/app/Assessment.java
src/main/java/edu/iu/terracotta/model/app/Assignment.java
src/main/java/edu/iu/terracotta/model/app/RetakeDetails.java
src/main/java/edu/iu/terracotta/service/app/SubmissionService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/SubmissionServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImplTest.java

TCOTA-572 TCOTA-581 fix max submission attempts allowed logic

---

src/main/java/edu/iu/terracotta/controller/app/AnswerController.java
src/main/java/edu/iu/terracotta/controller/app/AssessmentController.java
src/main/java/edu/iu/terracotta/controller/app/ParticipantController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionController.java
src/main/java/edu/iu/terracotta/controller/app/QuestionSubmissionController.java
src/main/java/edu/iu/terracotta/model/app/Assessment.java
src/main/java/edu/iu/terracotta/service/app/AnswerService.java
src/main/java/edu/iu/terracotta/service/app/AssessmentService.java
src/main/java/edu/iu/terracotta/service/app/QuestionService.java
src/main/java/edu/iu/terracotta/service/app/impl/AnswerServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssessmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/QuestionServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/SubmissionServiceImpl.java
src/main/java/edu/iu/terracotta/service/app/impl/TreatmentServiceImpl.java
src/test/java/edu/iu/terracotta/service/app/impl/QuestionServiceImplTest.java

Response always had correct = null in the answers object if submission_id parameter was passed in. Also, removed unnecessary student param from the service call.

TCOTA-577 TCOTA-588 fix incorrect correct answers response

---

src/main/java/edu/iu/terracotta/model/app/Assessment.java

Fixed issue due to Java's Instant.now() timezone weirdness. Also, cleaned up the comparison logic.

TCOTA-583 fixing date comparison issues on displaying student responses

---

pom.xml
src/main/java/edu/iu/terracotta/repository/AllRepositories.java
src/main/java/edu/iu/terracotta/repository/CanvasAPITokenRepository.java
src/main/java/edu/iu/terracotta/security/app/APIOAuthProviderProcessingFilter.java
src/main/java/edu/iu/terracotta/service/app/ScheduledService.java
src/main/java/edu/iu/terracotta/service/app/impl/AssignmentServiceImpl.java
src/main/java/edu/iu/terracotta/service/caliper/impl/CaliperServiceImpl.java
src/main/java/edu/iu/terracotta/service/canvas/impl/CanvasAPIClientImpl.java
src/main/java/edu/iu/terracotta/service/lti/impl/LTIJWTServiceImpl.java

NO_JIRA remove token logging
